<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1547154863003" stop="1547154938315">
  <name>test</name>
  <labels/>
  <test-cases>
    <test-case start="1547154863003" status="passed" stop="1547154873141">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact.test_add_contact[None:;;;]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154873142" status="passed" stop="1547154874654">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact.test_add_contact[None:FirstNameFaXPEadLL;MiddleNamehNYlKYMmN;LastNamejILa;NickName]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154874655" status="passed" stop="1547154876217">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact.test_add_contact[None:FirstNamePmE;MiddleNameUJmJcBKXLluZHEbDVi;LastNameSyS;NickNamecuOK]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154876219" status="passed" stop="1547154877377">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact.test_add_contact[None:FirstNameNg;MiddleNamefWOfST;LastName;NickNameIfBRR]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154877378" status="passed" stop="1547154878609">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact.test_add_contact[None:FirstNameZWQQz;MiddleNameimPWxxPndzRcV;LastNameNPXcD;NickName]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154878612" status="passed" stop="1547154879934">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact.test_add_contact[None:FirstNamewasCHhX;MiddleNamedFSKDVxKACP;LastNameJmkbknW;NickName]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154879941" status="passed" stop="1547154883536">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact_simple.test_add_contact</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154883538" status="passed" stop="1547154884043">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact_simple.test_open_contact_view_by_index</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154884044" status="failed" stop="1547154884491">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_contact_to_group.test_add_contact_to_group</name>
      <failure>
        <message>TypeError: get_contacts_in_group() missing 1 required positional argument: 'group'</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;
db = &lt;fixture.db.DbFixture object at 0x03AA1B30&gt;
orm = &lt;fixture.orm.ORMFixture object at 0x03A7C3B0&gt;, check_ui = False

    def test_add_contact_to_group(app, db, orm, check_ui):
        app.open_home_page()
        if len(db.get_contact_list()) == 0:
            app.contact.create(Contact(first_name="Vasia"))
        if len(db.get_group_list()) == 0:
            app.group.create(Group(name="test"))
&gt;       old_contacts = orm.get_contacts_in_group()
E       TypeError: get_contacts_in_group() missing 1 required positional argument: 'group'

test\test_add_contact_to_group.py:13: TypeError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154884494" status="passed" stop="1547154888612">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_group.test_add_group[None:;;]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154888613" status="passed" stop="1547154892474">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_group.test_add_group[None:nameH;headeruGbfIHfpZRvYStlB;footerXgOrUKYc]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154892477" status="passed" stop="1547154896342">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_group.test_add_group[None:namemvFPBTRk;headerxdpQuzZkqJN;footerJdEKoFC]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154896346" status="passed" stop="1547154900161">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_group.test_add_group[None:name;headeriTVRDfockhpuRK;footerVshizGseYbanFFwDcs]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154900162" status="passed" stop="1547154904040">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_group.test_add_group[None:namebHMFwY;headermowH;footertvVYULGNiX]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154904041" status="passed" stop="1547154907877">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_add_group.test_add_group[None:nameeP;headerOREsOXkgmBRnA;footercUjoqeHYGJk]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154907878" status="passed" stop="1547154911419">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_db_matches_ui.test_group_list</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154911435" status="failed" stop="1547154914499">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_db_matches_ui.test_contact_list</name>
      <failure>
        <message>AssertionError: assert [] == [256:First name;None;Lastnam...ne;Lastname{hs--i;None, ...]
  Right contains more items, first extra item: 256:First name;None;Lastname7O$a~_;None
  Use -v to get the full diff</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;
db = &lt;fixture.db.DbFixture object at 0x03AA1B30&gt;

    def test_contact_list(app, db):
        ui_list = app.contact.get_contact_list()
    
        def clean(contact):
            return Contact(id=contact.id, lastname=contact.lastname.strip(), first_name=contact.first_name.strip())
        db_list = map(clean, db.get_contact_list())
&gt;       assert sorted(ui_list, key=Contact.id_or_max) == sorted(db_list, key=Contact.id_or_max)
E       assert [] == [256:First name;None;Lastnam...ne;Lastname{hs--i;None, ...]
E         Right contains more items, first extra item: 256:First name;None;Lastname7O$a~_;None
E         Use -v to get the full diff

test\test_db_matches_ui.py:20: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154914499" status="failed" stop="1547154915290">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_del_contact.test_del_contact</name>
      <failure>
        <message>AssertionError: assert (0 - 1) == 52
 +  where 0 = len([])
 +  and   52 = &lt;bound method ContactHelper.count of &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;&gt;()
 +    where &lt;bound method ContactHelper.count of &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;&gt; = &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;.count
 +      where &lt;fixture.contact.ContactHelper object at 0x032448D0&gt; = &lt;fixture.application.Application object at 0x03AA13B0&gt;.contact</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_del_contact(app):
        app.open_home_page()
        if app.contact.count() == 0:
            app.contact.create(Contact(first_name="Vasia"))
        old_contacts = app.contact.get_contact_list()
        app.contact.delete_first_contact()
        app.open_home_page()
&gt;       assert len(old_contacts) - 1 == app.contact.count()
E       assert (0 - 1) == 52
E        +  where 0 = len([])
E        +  and   52 = &lt;bound method ContactHelper.count of &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;&gt;()
E        +    where &lt;bound method ContactHelper.count of &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;&gt; = &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;.count
E        +      where &lt;fixture.contact.ContactHelper object at 0x032448D0&gt; = &lt;fixture.application.Application object at 0x03AA13B0&gt;.contact

test\test_del_contact.py:13: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154915310" status="passed" stop="1547154915925">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_del_contact.test_del_some_contact</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154915929" status="passed" stop="1547154916561">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_del_contact_simple.test_del_contact_simple</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154916562" status="passed" stop="1547154923576">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_del_group.test_delete_first_group</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154923592" status="passed" stop="1547154926973">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_del_group.test_delete_some_group</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154926975" status="failed" stop="1547154930095">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_mails.test_mails_on_home_page</name>
      <failure>
        <message>IndexError: list index out of range</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_mails_on_home_page(app):
&gt;       contact_from_home_page = app.contact.get_contact_list()[0]
E       IndexError: list index out of range

test\test_mails.py:4: IndexError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154930095" status="failed" stop="1547154930405">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_modify_contact.test_modify_contact_first_name</name>
      <failure>
        <message>ValueError: empty range for randrange()</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_modify_contact_first_name(app):
        app.open_home_page()
        if app.contact.count() == 0:
            app.contact.create(Contact(first_name="Vasia"))
        old_contacts = app.contact.get_contact_list()
&gt;       index = randrange(len(old_contacts))

test\test_modify_contact.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;random.Random object at 0x005D3F40&gt;, start = 0, stop = None, step = 1
_int = &lt;class 'int'&gt;

    def randrange(self, start, stop=None, step=1, _int=int):
        """Choose a random item from range(start, stop[, step]).
    
        This fixes the problem with randint() which includes the
        endpoint; in Python this is usually not what you want.
    
        """
    
        # This code is a bit messy to make it fast for the
        # common case while still doing adequate error checking.
        istart = _int(start)
        if istart != start:
            raise ValueError("non-integer arg 1 for randrange()")
        if stop is None:
            if istart &gt; 0:
                return self._randbelow(istart)
&gt;           raise ValueError("empty range for randrange()")
E           ValueError: empty range for randrange()

env\lib\random.py:190: ValueError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154930405" status="failed" stop="1547154934164">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_modify_group.test_modify_group_name</name>
      <failure>
        <message>AssertionError: assert [187:New Name...p footer, ...] == [187:New Name;...p footer, ...]
  At index 7 diff: 210:New Name;Group header;Group footer != 210:New group;Group header;Group footer
  Use -v to get the full diff</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;
db = &lt;fixture.db.DbFixture object at 0x03AA1B30&gt;

    def test_modify_group_name(app, db):
        if len(db.get_group_list()) == 0:
            app.group.create(Group(name="test"))
        old_groups = db.get_group_list()
        index = randrange(len(old_groups))
        group = Group(name="New group")
        group.id = old_groups[index].id
        app.group.modify_group_by_index(index, group)
        new_groups = db.get_group_list()
        old_groups[index] = group
&gt;       assert sorted(old_groups, key=Group.id_or_max) == sorted(new_groups, key=Group.id_or_max)
E       assert [187:New Name...p footer, ...] == [187:New Name;...p footer, ...]
E         At index 7 diff: 210:New Name;Group header;Group footer != 210:New group;Group header;Group footer
E         Use -v to get the full diff

test\test_modify_group.py:17: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154934168" status="failed" stop="1547154937670">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_modify_group.test_modify_group_header</name>
      <failure>
        <message>TypeError: modify_first_group() takes 1 positional argument but 2 were given</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_modify_group_header(app):
        if app.group.count() == 0:
            app.group.create(Group(name="test"))
        old_groups = app.group.get_group_list()
&gt;       app.group.modify_first_group(Group(header="New header"))
E       TypeError: modify_first_group() takes 1 positional argument but 2 were given

test\test_modify_group.py:24: TypeError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154937686" status="failed" stop="1547154937732">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_names.test_first_name_on_home_page</name>
      <failure>
        <message>IndexError: list index out of range</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_first_name_on_home_page(app):
&gt;       contact_from_home_page = app.contact.get_contact_list()[0]
E       IndexError: list index out of range

test\test_names.py:5: IndexError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154937732" status="failed" stop="1547154937764">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_names.test_lastname_on_home_page</name>
      <failure>
        <message>IndexError: list index out of range</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_lastname_on_home_page(app):
&gt;       contact_from_home_page = app.contact.get_contact_list()[0]
E       IndexError: list index out of range

test\test_names.py:11: IndexError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154937764" status="failed" stop="1547154937811">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_names.test_address_on_home_page</name>
      <failure>
        <message>IndexError: list index out of range</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_address_on_home_page(app):
&gt;       contact_from_home_page = app.contact.get_contact_list()[0]
E       IndexError: list index out of range

test\test_names.py:17: IndexError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154937811" status="failed" stop="1547154937842">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_names.test_contacts_on_home_page_vs_db</name>
      <failure>
        <message>AssertionError: assert [] == [256:First name ;None;Lastna...ne;Lastname{hs--i;None, ...]
  Right contains more items, first extra item: 256:First name ;None;Lastname7O$a~_;None
  Use -v to get the full diff</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;
db = &lt;fixture.db.DbFixture object at 0x03AA1B30&gt;

    def test_contacts_on_home_page_vs_db(app, db):
        contact_from_home_page = app.contact.get_contact_list()
        contact_from_db = db.get_contact_list()
&gt;       assert sorted(contact_from_home_page, key=Contact.id_or_max) == sorted(contact_from_db, key=Contact.id_or_max)
E       assert [] == [256:First name ;None;Lastna...ne;Lastname{hs--i;None, ...]
E         Right contains more items, first extra item: 256:First name ;None;Lastname7O$a~_;None
E         Use -v to get the full diff

test\test_names.py:25: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154937842" status="failed" stop="1547154937889">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_phones.test_phones_on_home_page</name>
      <failure>
        <message>IndexError: list index out of range</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_phones_on_home_page(app):
&gt;       contact_from_home_page = app.contact.get_contact_list()[0]
E       IndexError: list index out of range

test\test_phones.py:5: IndexError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1547154937904" status="broken" stop="1547154938315">
      <name>C:\Users\PStoiko\PycharmProjects\python_training_2\test.test_phones.test_phones_on_contact_view_page</name>
      <failure>
        <message>AttributeError: 'NoneType' object has no attribute 'group'</message>
        <stack-trace>app = &lt;fixture.application.Application object at 0x03AA13B0&gt;

    def test_phones_on_contact_view_page(app):
&gt;       contact_from_view_page = app.contact.get_contact_from_view_page(0)

test\test_phones.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;fixture.contact.ContactHelper object at 0x032448D0&gt;, index = 0

    def get_contact_from_view_page(self, index):
        wd = self.app.wd
        self.open_contact_view_by_index(index)
        text = wd.find_element_by_id("content").text
&gt;       home_phone = re.search("H: (.*)", text).group(1)
E       AttributeError: 'NoneType' object has no attribute 'group'

fixture\contact.py:174: AttributeError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7356-MainThread"/>
        <label name="host" value="IE11-PStoiko-VM"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
